{
 "title": "MonitoringDemo Overview",
 "tags": [ "monitoring" ],
 "refresh": "5s",
 "panels": [
  {
   "title": "App Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "up{job=\"monitoringdemo\"}"
    }
   ]
  },
  {
   "title": "App Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{container=\"monitoringdemo\"}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"monitoringdemo\"}[1m])"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"monitoringdemo\", status!~\"2..\"}[1m])"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"monitoringdemo\"}[1m]) / rate(http_request_duration_seconds_count{job=\"monitoringdemo\"}[1m])"
    }
   ]
  },
  {
   "title": "Custom Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "monitoringdemo_custom_requests_total"
    }
   ]
  },
  {
   "title": "Processing Time (Histogram)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(monitoringdemo_processing_seconds_sum[1m]) / rate(monitoringdemo_processing_seconds_count[1m])"
    }
   ]
  }
 ]
}